server:
  port: 5000
spring:
  application:
    name: product-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///aigou_product?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver